[feature/69]  css-in-js 를 위한 CustomStyledcComponent 모듈 구현
woowa-techcamp-2021/store-5 pull request #70
Opened 2021-08-14 14:34 UTC by peanut-lover

## :bookmark_tabs: 제목

라이브러리없이 css-in-js 작업을 위해 `CustomStyledComponent` 의 기본적인 기능만 하는 형태로 구현했습니다.

<img width="465" alt="스크린샷 2021-08-14 오후 11 33 56" src="https://user-images.githubusercontent.com/20085849/129449748-5b21b8fc-d8d7-48b2-bc31-953dc899267b.png">

## :heavy_check_mark: 셀프 체크리스트

> ~최소 1명 이상의 assign을 받아야만 Merge 가능합니다.~

- [x] Warning Message가 발생하지 않았나요?
- [x] Coding Convention을 준수했나요?
- [x] 'npm run lint'나 'yarn lint'를 실행하였나요?

## :speech_balloon: 작업 내용

> 구현 내용 및 작업 했던 내역
- [x] CustomRouter 위치 이동 (lib 디렉토리를 활용하기위해)
- [x] styled component 기본적인 인터페이스 흉내내기
- [x] 기본적인 동작 테스트케이스로 작성하기

## :construction: PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

-  [VSCode Plugin vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components)의 컬러 하이라이트가 제대로 동작하려면  import 해서 가져올때 `styled`라는 이름으로 가져와야지 동작합니다. 
- 아직 `styled.div` 형태로 동작하는 인터페이스는 구현하지않았습니다. 추후에 구현할지는 아직 결정되지않았습니다. (방법을 라이브러리 코드를 확인해보면서 찾아야할듯합니다.)

2021-08-15 03:27 UTC, Kwongiseok approved these changes
저는 이해 다 됐습니다! :) 
고생하셨습니다!!

styled.div 형태로 구현할 필요없어보일 듯 합니다! 
styled('div') 이 더 가독성이 좋아보이는,, 개인적인 의견입니다 ㅋㅋ

2021-08-15 07:06 UTC, ondal1997 approved these changes
수고하셨습니다. tagged template literal을 좀 학습하고 다시 읽어봐야겠어요

2021-08-15 07:06 UTC, ondal1997 commented on frontend/client/src/lib/CustomStyledComponent/index.ts
> +};
함수 안에 return 키워드가 3개! 커허허ㅓ 눈이 아파요

2021-08-15 07:10 UTC, peanut-lover commented on frontend/client/src/lib/CustomStyledComponent/index.ts
> +};
걱정마세요 문서로 쉽게남겨둘게요

2021-08-15 08:08 UTC, ondal1997 requested changes
제가 로직의 결함을 발견한것 같은데 한번 확인해주실수있나요??

2021-08-15 08:08 UTC, ondal1997 commented on frontend/client/src/lib/CustomStyledComponent/index.ts
> +  };
이 함수의 결과로 받은 컴포넌트가 렌더링 될때마다 css 룰이 추가되는것 같은데, 한번 확인해주실래요?

2021-08-15 08:10 UTC, ondal1997 commented on frontend/client/src/lib/CustomStyledComponent/index.ts
> +  };
```js
export const styled = (tag: keyof ReactHTML) => {
  return function styledTemplate<P = {}>(rules: TemplateStringsArray, ...args: StylePropsFn<P>[]): React.FC<P> {
      const resolved = resolveRule<P>(rules, args, props);
      const className = css(resolved);
    return (props) => {
      return React.createElement(tag, { className, ...props });
    };
  };
```

이렇게 수정되어야할듯합니다.

2021-08-15 08:17 UTC, Kwongiseok commented on frontend/client/src/lib/CustomStyledComponent/index.ts
> +  };
props에 의해서도 적용이 되어야하니까 렌더링이 될 때 마다 새롭게 만들어져야하는것이 맞지 않을까요?!..

2021-08-15 08:19 UTC, peanut-lover commented on frontend/client/src/lib/CustomStyledComponent/index.ts
> +  };
맞아요 컴포넌트 제거시 룰도 제거해주는 로직이 오히려 필요하죠

2021-08-15 11:47 UTC, peanut-lover commented
@Kwongiseok  @ondal1997  @kowoohyuk  어느정도 기능하는데 문제 없어보여서 마지막으로 리뷰 요청드립니다. 😊

2021-08-16 02:36 UTC, ondal1997 approved these changes
수고하셨습니다.

2021-08-16 02:36 UTC, merged

2021-08-16 02:41 UTC, kowoohyuk commented on frontend/client/src/lib/CustomStyledComponent/CuteomStyledComponent.spec.tsx
> +    expect(mockLatestStyle.includes('color: red')).toEqual(true);
스타일은 어떻게 테스트하나 궁금한 점이 있었는데 나중에 알아보려 했더니 여기에 이미 예제를 가져다 놓으셨네요!  
감사합니다 :)

2021-08-16 02:45 UTC, kowoohyuk reviewed
CustomStyledComponent의 index 부분을 자세히 톺아보고 궁금한 점이 생기면 질문하도록 하겠습니다

수고하셨어요!  👍

2021-08-17 15:54 UTC, gomjellie commented
![키야](https://user-images.githubusercontent.com/13645032/129759512-e51f61af-a369-4e4d-851e-207873b1eea1.png)

잘먹겠습니다~